server:
  port: 8090

spring:
  profiles:
    active: develop
  jpa:
    show_sql: false
    database: H2
    defer-datasource-initialization: true
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE;IGNORECASE=TRUE
  h2:
    console:
      enabled: true
